// Extension groups (overview/03 Parts B & D) — merged into EP by endpoints.ts.

export const EP_EXT = {
  farm: {
    plots: '/farm/plots',
    plot: (id: string) => `/farm/plots/${id}`,
    cropCycles: '/farm/crop-cycles',
    cropCycle: (id: string) => `/farm/crop-cycles/${id}`,
  },
  soilTests: { book: '/soil-tests/book', my: '/soil-tests/my' },
  market: {
    lots: '/market/lots',
    lotsMy: '/market/lots/my',
    lot: (id: string) => `/market/lots/${id}`,
    requirements: '/market/requirements',
    requirement: (id: string) => `/market/requirements/${id}`,
  },
  seller: {
    rates: '/seller/rates',
    ratesMy: '/seller/rates/my',
    rate: (id: string) => `/seller/rates/${id}`,
    inventory: '/seller/inventory',
    inventoryItem: (id: string) => `/seller/inventory/${id}`,
    sales: '/seller/sales',
    procurements: '/seller/procurements',
    markPaid: (id: string) => `/seller/procurements/${id}/mark-paid`,
    ledgers: '/seller/ledgers',
    ledger: (buyerKey: string) => `/seller/ledgers/${buyerKey}`,
    ledgerPayments: (buyerKey: string) => `/seller/ledgers/${buyerKey}/payments`,
  },
  broker: {
    deals: '/broker/deals',
    deal: (id: string) => `/broker/deals/${id}`,
    dealMessages: (id: string) => `/broker/deals/${id}/messages`,
    leads: '/broker/leads',
    lead: (id: string) => `/broker/leads/${id}`,
    commissions: '/broker/commissions',
    commission: (id: string) => `/broker/commissions/${id}`,
  },
  land: {
    plots: '/land/plots',
    plot: (id: string) => `/land/plots/${id}`,
    leases: '/land/leases',
    lease: (id: string) => `/land/leases/${id}`,
    leasePayments: (id: string) => `/land/leases/${id}/payments`,
    leaseRemind: (id: string) => `/land/leases/${id}/payments/remind`,
    agreementPdf: (id: string) => `/land/leases/${id}/agreement-pdf`,
    leaseSign: (id: string) => `/land/leases/${id}/sign`,
    listings: '/land/listings',
    listingsMy: '/land/listings/my',
    listing: (id: string) => `/land/listings/${id}`,
    listingLeaseRequests: (id: string) => `/land/listings/${id}/lease-requests`,
    leaseRequests: '/land/lease-requests',
    leaseRequestsMy: '/land/lease-requests/my',
    leaseRequestAccept: (id: string) => `/land/lease-requests/${id}/accept`,
    leaseRequestReject: (id: string) => `/land/lease-requests/${id}/reject`,
  },
  notifications: { list: '/notifications', read: '/notifications/read' },
  search: '/search',
  addresses: {
    root: '/addresses',
    detail: (id: string) => `/addresses/${id}`,
  },
  bankAccounts: {
    root: '/bank-accounts',
    verify: (id: string) => `/bank-accounts/${id}/verify`,
    primary: (id: string) => `/bank-accounts/${id}/primary`,
    detail: (id: string) => `/bank-accounts/${id}`,
  },
  chats: {
    root: '/chats',
    messages: (id: string) => `/chats/${id}/messages`,
  },
  support: {
    threads: '/support/threads',
    messages: (id: string) => `/support/threads/${id}/messages`,
    resolve: (id: string) => `/support/threads/${id}/resolve`,
  },
  devices: {
    root: '/devices',
    detail: (token: string) => `/devices/${token}`,
  },
  ratings: { root: '/ratings', summary: '/ratings/summary' },
  speech: { stt: '/speech/stt', tts: '/speech/tts' },
} as const;
