// Path constants for every endpoint in endpoints.md + docs/overview/03 (Parts B & D).
// Paths omit the /v1 prefix — the client prepends the base URL.
import { EP_EXT } from './endpoints-ext';

export const EP = {
  auth: {
    otpSend: '/auth/otp/send',
    otpVerify: '/auth/otp/verify',
    login: '/auth/login',
    mpinReset: '/auth/mpin/reset',
    mpinReverify: '/auth/mpin/reverify',
    biometric: '/auth/biometric',
    refresh: '/auth/refresh',
    logout: '/auth/logout',
    register: '/auth/register',
    sessions: '/auth/sessions',
    session: (id: string) => `/auth/sessions/${id}`,
  },
  users: {
    me: '/users/me',
    farmBoundary: '/users/me/farm-boundary',
    profiles: '/users/me/profiles',
    profile: (type: string) => `/users/me/profiles/${type}`,
    profileActivate: (type: string) => `/users/me/profiles/${type}/activate`,
    profilePrimary: (type: string) => `/users/me/profiles/${type}/primary`,
    settings: '/users/me/settings',
    consents: '/users/me/consents',
    dashboard: (profileType: string) => `/users/me/dashboard/${profileType}`,
    bookings: '/users/me/bookings',
    blocks: '/users/me/blocks',
    block: (uid: string) => `/users/me/blocks/${uid}`,
    export: '/users/me/export',
    report: (id: string) => `/users/${id}/report`,
  },
  reference: {
    geoReverse: '/geo/reverse',
    regionCrops: '/regions/crops',
    languages: '/languages',
    msp: '/reference/msp',
  },
  appConfig: '/app-config',
  mandi: {
    prices: '/mandi/prices',
    priceHistory: '/mandi/prices/history',
    vyapariRates: '/mandi/vyapari-rates',
    compare: '/mandi/compare',
    list: '/mandi/list',
  },
  advisory: {
    saturation: '/advisory/saturation',
    diseaseScan: '/advisory/disease-scan',
    pestRadar: '/advisory/pest-radar',
    npk: '/advisory/npk',
    sowingIntent: '/advisory/sowing-intent',
  },
  chatbot: {
    messages: '/chatbot/messages',
    history: '/chatbot/history',
    handoff: '/chatbot/handoff',
  },
  weather: { current: '/weather', forecast: '/weather/forecast' },
  tasks: {
    today: '/tasks/today',
    list: '/tasks',
    complete: (id: string) => `/tasks/${id}/complete`,
    snooze: (id: string) => `/tasks/${id}/snooze`,
    urgentComplete: '/tasks/urgent/complete',
  },
  products: {
    list: '/products',
    detail: (id: string) => `/products/${id}`,
    certificate: (id: string) => `/products/${id}/certificate`,
    reviews: (id: string) => `/products/${id}/reviews`,
    review: (id: string, rid: string) => `/products/${id}/reviews/${rid}`,
  },
  cart: {
    root: '/cart',
    items: '/cart/items',
    item: (productId: string) => `/cart/items/${productId}`,
  },
  orders: {
    root: '/orders',
    detail: (id: string) => `/orders/${id}`,
    cancel: (id: string) => `/orders/${id}/cancel`,
  },
  payments: {
    razorpayOrder: '/payments/razorpay/order',
    razorpayVerify: '/payments/razorpay/verify',
    razorpayRefund: '/payments/razorpay/refund',
  },
  contracts: {
    list: '/contracts',
    detail: (id: string) => `/contracts/${id}`,
    accept: (id: string) => `/contracts/${id}/accept`,
  },
  transport: {
    vehicles: '/transport/vehicles',
    vehiclesMy: '/transport/vehicles/my',
    vehicle: (id: string) => `/transport/vehicles/${id}`,
    vehicleCalendar: (id: string) => `/transport/vehicles/${id}/calendar`,
    vehicleAvailability: (id: string) => `/transport/vehicles/${id}/availability`,
    fareEstimate: '/transport/fare-estimate',
    bookings: '/transport/bookings',
    booking: (id: string) => `/transport/bookings/${id}`,
    bookingAccept: (id: string) => `/transport/bookings/${id}/accept`,
    bookingReject: (id: string) => `/transport/bookings/${id}/reject`,
    settlements: '/transport/settlements',
    settlementsCurrent: '/transport/settlements/current',
  },
  pnl: {
    summary: '/pnl/summary',
    crops: '/pnl/crops',
    addExpense: (id: string) => `/pnl/crops/${id}/expenses`,
    breakEven: '/pnl/break-even',
  },
  diary: {
    entries: '/diary/entries',
    entry: (id: string) => `/diary/entries/${id}`,
    report: '/diary/report',
  },
  water: {
    schedule: '/water/schedule',
    groundwater: '/water/groundwater',
    canalRotation: '/water/canal-rotation',
    pmksyCalculator: '/water/pmksy-calculator',
  },
  schemes: {
    list: '/schemes',
    apply: (id: string) => `/schemes/${id}/apply`,
    portals: '/schemes/portals',
  },
  vault: {
    documents: '/vault/documents',
    document: (id: string) => `/vault/documents/${id}`,
  },
  finance: {
    creditScore: '/finance/credit-score',
    loanCalculator: '/finance/loan-calculator',
    kcc: '/finance/kcc',
    loans: '/finance/loans',
    loansApply: '/finance/loans/apply',
  },
  insurance: {
    policies: '/insurance/policies',
    policiesApply: '/insurance/policies/apply',
    certificate: (id: string) => `/insurance/policies/${id}/certificate`,
    rates: '/insurance/rates',
    claims: '/insurance/claims',
    claim: (id: string) => `/insurance/claims/${id}`,
    claimAppeal: (id: string) => `/insurance/claims/${id}/appeal`,
  },
  landRecords: {
    search: '/land-records/search',
    pdf: (id: string) => `/land-records/${id}/pdf`,
    import: (id: string) => `/land-records/${id}/import`,
  },
  equipment: {
    list: '/equipment',
    create: '/equipment',
    detail: (id: string) => `/equipment/${id}`,
    slots: (id: string) => `/equipment/${id}/slots`,
    slotTemplates: (id: string) => `/equipment/${id}/slot-templates`,
    bookSlot: (id: string) => `/equipment/slots/${id}/book`,
    waitlist: (id: string) => `/equipment/slots/${id}/waitlist`,
    bookings: '/equipment/bookings',
    booking: (id: string) => `/equipment/bookings/${id}`,
    bookingApprove: (id: string) => `/equipment/bookings/${id}/approve`,
    bookingReject: (id: string) => `/equipment/bookings/${id}/reject`,
    ownerFleet: '/equipment/owner/fleet',
    maintenance: (id: string) => `/equipment/${id}/maintenance`,
    maintenanceEntry: (id: string, mid: string) => `/equipment/${id}/maintenance/${mid}`,
  },
  fpo: {
    me: '/fpo/me',
    pools: '/fpo/pools',
    poolJoin: (id: string) => `/fpo/pools/${id}/join`,
    machinery: '/fpo/machinery',
    nearby: '/fpo/nearby',
    joinRequest: (id: string) => `/fpo/${id}/join-request`,
    myMembership: '/fpo/my-membership',
  },
  livestock: {
    gaushalas: '/gaushalas',
    manureOrder: (id: string) => `/gaushalas/${id}/manure-order`,
    nurseries: '/nurseries',
    vets: '/vets',
    vetBook: (id: string) => `/vets/${id}/book`,
    dairyProducts: '/dairy-products',
    dairyOrder: (id: string) => `/dairy-products/${id}/order`,
  },
  content: {
    news: '/news',
    channels: '/channels',
    channelChat: (id: string) => `/channels/${id}/chat`,
    workshops: '/workshops',
    workshopEnroll: (id: string) => `/workshops/${id}/enroll`,
    expertTalks: '/expert-talks',
    talkRegister: (id: string) => `/expert-talks/${id}/register`,
    talkQuestions: (id: string) => `/expert-talks/${id}/questions`,
    videos: '/videos',
    blogs: '/blogs',
    blogBookmark: (id: string) => `/blogs/${id}/bookmark`,
    blogLike: (id: string) => `/blogs/${id}/like`,
  },
  tree: {
    articles: '/tree/articles',
    ngos: '/tree/ngos',
    saplingRequest: (id: string) => `/tree/ngos/${id}/sapling-request`,
    biofuel: '/tree/biofuel',
    careGuides: '/tree/care-guides',
  },
  gamification: {
    status: '/gamification/status',
    rewards: '/gamification/rewards',
    redeem: '/gamification/redeem',
    ledger: '/gamification/ledger',
  },
  referrals: {
    root: '/referrals',
    invite: '/referrals/invite',
    validate: '/referrals/validate',
  },
  climate: {
    carbonPotential: '/climate/carbon-potential',
    resilientVarieties: '/climate/resilient-varieties',
  },
  postHarvest: {
    coldStorage: '/post-harvest/cold-storage',
    book: (id: string) => `/post-harvest/cold-storage/${id}/book`,
    bookingsMy: '/post-harvest/cold-storage/bookings/my',
    booking: (id: string) => `/post-harvest/cold-storage/bookings/${id}`,
    grade: '/post-harvest/grade',
  },
  women: {
    shg: '/women/shg',
    shgDeposit: '/women/shg/deposit',
    homeEnterprise: '/women/home-enterprise',
  },
  dashboard: { home: '/dashboard/home' },
  sync: '/sync',
  ...EP_EXT,
} as const;
