ACCESS_MAP: dict[str, set[str]] = {
    "farmer": {
        "home",
        "gyanHub",
        "krishiRatna",
        "mandi",
        "marketplace",
        "buyers",
        "advisory",
        "profitLoss",
        "water",
        "schemes",
        "finance",
        "womenFarmer",
        "fpo",
        "equipment",
        "landLegal",
        "climate",
        "postHarvest",
        "treePlantation",
        "liveChannels",
        "agriNews",
        "livestockDairy",
        "farmDiary",
        "referEarn",
        "cropInsurance",
    },
    "farmLandlord": {
        "landlordHome",
        "landLegal",
        "schemes",
        "finance",
        "cropInsurance",
        "profitLoss",
        "krishiRatna",
        "gyanHub",
        "marketplace",
        "treePlantation",
        "agriNews",
        "farmDiary",
        "referEarn",
    },
    "transport": {
        "transportHome",
        "postHarvest",
        "marketplace",
        "finance",
        "krishiRatna",
        "gyanHub",
        "liveChannels",
        "agriNews",
        "referEarn",
    },
    "seller": {
        "sellerHome",
        "mandi",
        "buyers",
        "marketplace",
        "finance",
        "profitLoss",
        "krishiRatna",
        "gyanHub",
        "postHarvest",
        "livestockDairy",
        "treePlantation",
        "agriNews",
        "referEarn",
    },
    "equipmentRental": {
        "equipmentOwnerHome",
        "equipment",
        "finance",
        "profitLoss",
        "krishiRatna",
        "gyanHub",
        "liveChannels",
        "agriNews",
        "referEarn",
    },
    "broker": {
        "brokerHome",
        "mandi",
        "buyers",
        "finance",
        "profitLoss",
        "krishiRatna",
        "gyanHub",
        "liveChannels",
        "agriNews",
        "referEarn",
    },
}

DEFAULT_HOME: dict[str, str] = {
    "farmer": "home",
    "farmLandlord": "landlordHome",
    "transport": "transportHome",
    "seller": "sellerHome",
    "equipmentRental": "equipmentOwnerHome",
    "broker": "brokerHome",
}
