// Multi-Profile System — Route Access Control Layer

import '../models/user_profile_type.dart';

class ProfileRoutes {
  static const Map<UserProfileType, Set<String>> _accessMap = {
    UserProfileType.farmer: {
      'home',
      'profileEdit',
      'gyanHub',
      'krishiRatna',
      'mandi',
      'sellProduce',
      'marketplace',
      'orderTracking',
      'addressBook',
      'buyers',
      'advisory',
      'profitLoss',
      'water',
      'schemes',
      'finance',
      'bankAccounts',
      'loanTracking',
      'loanDetail',
      'landlordPlots',
      'landlordLeases',
      'landlordRent',
      'womenFarmer',
      'fpo',
      'equipment',
      'landLegal',
      'climate',
      'postHarvest',
      'treePlantation',
      'liveChannels',
      'agriNews',
      'livestockDairy',
      'farmDiary',
      'referEarn',
      'cropInsurance',
      'myBookings',
      'loadBoard',
      'liveTracking',
      'biltyView',
      'buyDemands',
      'myOffers',
      'notifications',
      'settings',
      'helpSupport',
      'accountDelete',
    },
    UserProfileType.farmLandlord: {
      'landlordHome',
      'profileEdit',
      'landLegal',
      'schemes',
      'finance',
      'bankAccounts',
      'cropInsurance',
      'myBookings',
      'profitLoss',
      'landlordPlots',
      'landlordLeases',
      'landlordRent',
      'landListings',
      'leaseRequests',
      'krishiRatna',
      'gyanHub',
      'marketplace',
      'orderTracking',
      'addressBook',
      'treePlantation',
      'agriNews',
      'farmDiary',
      'referEarn',
      'notifications',
      'settings',
      'helpSupport',
      'accountDelete',
    },
    UserProfileType.transport: {
      'transportHome',
      'tripDetail',
      'vehicleManage',
      'vehicleCalendar',
      'bookingInbox',
      'loadBoard',
      'transporterProfile',
      'liveTracking',
      'biltyView',
      'myBookings',
      'profileEdit',
      'postHarvest',
      'marketplace',
      'orderTracking',
      'addressBook',
      'finance',
      'bankAccounts',
      'settlements',
      'krishiRatna',
      'gyanHub',
      'liveChannels',
      'agriNews',
      'referEarn',
      'notifications',
      'settings',
      'helpSupport',
      'accountDelete',
    },
    UserProfileType.seller: {
      'sellerHome',
      'sellerProducts',
      'sellerAnalytics',
      'profileEdit',
      'mandi',
      'buyers',
      'marketplace',
      'orderTracking',
      'myBookings',
      'addressBook',
      'finance',
      'bankAccounts',
      'profitLoss',
      'krishiRatna',
      'gyanHub',
      'postHarvest',
      'livestockDairy',
      'treePlantation',
      'agriNews',
      'referEarn',
      'notifications',
      'settings',
      'helpSupport',
      'accountDelete',
    },
    UserProfileType.equipmentRental: {
      'equipmentOwnerHome',
      'machineManage',
      'slotCalendarManage',
      'profileEdit',
      'equipment',
      'finance',
      'bankAccounts',
      'settlements',
      'profitLoss',
      'krishiRatna',
      'gyanHub',
      'liveChannels',
      'agriNews',
      'referEarn',
      'notifications',
      'settings',
      'helpSupport',
      'accountDelete',
    },
    UserProfileType.broker: {
      'brokerHome',
      'profileEdit',
      'mandi',
      'buyers',
      'finance',
      'bankAccounts',
      'settlements',
      'profitLoss',
      'krishiRatna',
      'gyanHub',
      'liveChannels',
      'agriNews',
      'referEarn',
      'notifications',
      'settings',
      'helpSupport',
      'accountDelete',
    },
    UserProfileType.instructor: {
      'instructorHome',
      'courses',
      'courseDetail',
      'myLibrary',
      'profileEdit',
      'finance',
      'bankAccounts',
      'settlements',
      'krishiRatna',
      'gyanHub',
      'agriNews',
      'referEarn',
      'notifications',
      'settings',
      'helpSupport',
      'accountDelete',
    },
    UserProfileType.dairyManager: {
      'dairyManagerHome',
      'livestock',
      'livestockDairy',
      'dairyConsole',
      'gaushalaConsole',
      'vetNetwork',
      'profileEdit',
      'finance',
      'bankAccounts',
      'settlements',
      'krishiRatna',
      'gyanHub',
      'agriNews',
      'referEarn',
      'notifications',
      'settings',
      'helpSupport',
      'accountDelete',
    },
    UserProfileType.bankManager: {
      'bankManagerHome',
      'loanDashboard',
      'loanReview',
      'profileEdit',
      'finance',
      'bankAccounts',
      'settlements',
      'agriNews',
      'referEarn',
      'krishiRatna',
      'gyanHub',
      'notifications',
      'settings',
      'helpSupport',
      'accountDelete',
    },
    UserProfileType.insuranceProvider: {
      'insuranceProviderHome',
      'cropInsurance',
      'insurancePolicyReview',
      'insuranceClaimReview',
      'profileEdit',
      'finance',
      'bankAccounts',
      'settlements',
      'agriNews',
      'referEarn',
      'krishiRatna',
      'gyanHub',
      'notifications',
      'settings',
      'helpSupport',
      'accountDelete',
    },
    UserProfileType.coldStorageProvider: {
      'coldStorageHome',
      'postHarvest',
      'profileEdit',
      'myBookings',
      'finance',
      'bankAccounts',
      'settlements',
      'agriNews',
      'referEarn',
      'krishiRatna',
      'gyanHub',
      'notifications',
      'settings',
      'helpSupport',
      'accountDelete',
    },
    UserProfileType.customer: {
      'emarketHome',
      'marketplace',
      'orderTracking',
      'wishlist',
      'coupons',
      'addressBook',
      'myBookings',
      'profileEdit',
      'finance',
      'bankAccounts',
      'referEarn',
      'krishiRatna',
      'gyanHub',
      'agriNews',
      'liveChannels',
      'notifications',
      'settings',
      'helpSupport',
      'accountDelete',
    },
    UserProfileType.directBuyer: {
      'directBuyerHome',
      'demands',
      'demandDetail',
      'purchases',
      'purchaseDetail',
      'savedFarmers',
      'myOffers',
      'browseLots',
      'profileEdit',
      'finance',
      'bankAccounts',
      'profitLoss',
      'krishiRatna',
      'gyanHub',
      'agriNews',
      'marketplace',
      'orderTracking',
      'myBookings',
      'referEarn',
      'notifications',
      'settings',
      'helpSupport',
      'accountDelete',
    },
  };

  /// Course marketplace routes are accessible to every persona — any farmer
  /// (in any profile) can browse, buy and watch courses/podcasts.
  /// Wishlist, coupons & my-products are backed by "any logged-in user"
  /// endpoints, so they are universal too.
  ///
  /// 'wallet' & 'profileHub' are universal bottom-menu-bar destinations; both
  /// currently render placeholder screens until their modules land.
  static const Set<String> _universalRoutes = {
    'courses',
    'courseDetail',
    'myLibrary',
    'vetHome',
    'milkSlips',
    'wishlist',
    'coupons',
    'myProducts',
    'wallet',
    'profileHub',
  };

  /// Returns true if [profile] has permission to navigate to or view [route].
  static bool canAccess(UserProfileType profile, String route) {
    if (_universalRoutes.contains(route)) return true;
    final routes = _accessMap[profile];
    if (routes == null) return false;
    return routes.contains(route);
  }

  /// Returns the full set of accessible routes for [profile].
  static Set<String> routesFor(UserProfileType profile) {
    return _accessMap[profile] ?? _accessMap[UserProfileType.farmer]!;
  }

  /// Returns the default landing route for [profile].
  static String defaultRouteFor(UserProfileType profile) {
    return UserProfileRegistry.meta(profile).defaultHomeRoute;
  }
}
